import puppeteer from 'puppeteer-core';
const CHROME = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const OUT = 'C:\\Users\\David\\AppData\\Local\\Temp\\claude\\d--Project-Stock-Game\\1fb0636e-f7cf-4ca4-bcb8-3248f3ca07ef\\scratchpad';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox', '--hide-scrollbars'] });
const p = await b.newPage();
p.on('dialog', (d) => d.accept().catch(() => {}));
await p.setViewport({ width: 412, height: 892, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await p.goto('https://candlebike.vercel.app/', { waitUntil: 'networkidle2', timeout: 60000 });
await sleep(1200);
await p.click('#symbol-input');
await p.type('#symbol-input', 'AAPL', { delay: 70 });
await p.waitForSelector('#search-results li', { timeout: 15000 });
await p.click('#search-results li');
await p.waitForFunction(() => { const x = document.querySelector('#btn-start'); return x && !x.disabled; }, { timeout: 8000 });
await p.click('#btn-start');
await p.waitForFunction(() => document.querySelector('#screen-play')?.classList.contains('active'), { timeout: 30000 });
await sleep(2500);
await p.screenshot({ path: `${OUT}\\layout.png` });
console.log('saved layout.png');
await b.close();
